import type { OptionField } from '@/lib/options/schema';

/** The Meesho tool's option list. Because the UI renders off this declarative array (see
 * `src/lib/options/schema.ts`), editing this file is the *only* change needed to add, remove, or reorder
 * options; no component rework required. `simpleModeVisible: false` fields live under "More options". */
export const MEESHO_OPTIONS: OptionField[] = [
	{
		id: 'printerType',
		label: 'Printer',
		group: 'Print setup',
		controlType: 'segmented',
		choices: [
			{ value: 'label', label: 'Label printer', description: 'Thermal 3x5" / 4x6"', icon: 'label-printer' },
			{ value: 'a4', label: 'A4 printer', description: 'Regular paper', icon: 'a4-sheet' },
		],
		default: 'label',
		simpleModeVisible: true,
	},
	{
		id: 'labelSize',
		label: 'Label size',
		group: 'Print setup',
		controlType: 'segmented',
		choices: [
			{ value: 'thermal-3x5', label: '3 x 5"' },
			{ value: 'thermal-4x6', label: '4 x 6"' },
		],
		default: 'thermal-4x6',
		visibleIf: (config) => config.printerType === 'label',
		simpleModeVisible: true,
	},
	{
		id: 'labelsPerSheet',
		label: 'Labels per A4 sheet',
		group: 'Print setup',
		controlType: 'segmented',
		choices: [
			{ value: '1', label: '1 label', description: 'Largest print', icon: 'grid-1' },
			{ value: '2', label: '2 labels', description: 'Half sheet each', icon: 'grid-2' },
			{ value: '4', label: '4 labels', description: 'Saves paper', icon: 'grid-4' },
		],
		default: '4',
		visibleIf: (config) => config.printerType === 'a4',
		simpleModeVisible: true,
	},
	{
		id: 'cropMode',
		label: 'Invoice',
		group: 'Crop',
		controlType: 'segmented',
		choices: [
			{ value: 'label', label: 'Crop it away', description: 'Label only', icon: 'crop' },
			{ value: 'full', label: 'Keep it', description: 'Label + invoice', icon: 'full-page' },
		],
		default: 'label',
		helpText: 'Keep the invoice if you only want to sort or resize your labels without cutting anything off.',
		simpleModeVisible: true,
	},
	{
		id: 'sortKey',
		label: 'Sort labels by',
		group: 'Sort',
		controlType: 'select',
		choices: [
			{ value: 'original', label: 'Original order', description: 'Same order as your downloaded file', icon: 'sort-original' },
			{ value: 'sku', label: 'SKU', description: 'Same products together — fastest to pack', icon: 'sort-sku' },
			{ value: 'courier', label: 'Courier', description: 'One pile per delivery partner', icon: 'sort-courier' },
			{ value: 'destinationCode', label: 'Pickup hub', description: 'Grouped by destination hub', icon: 'sort-hub' },
			{ value: 'colorSize', label: 'Color, then size', description: 'Red S, Red M, then Blue S…', icon: 'sort-color' },
			{ value: 'sizeColor', label: 'Size, then color', description: 'S Blue, S Red, then M Blue…', icon: 'sort-size' },
		],
		default: 'original',
		simpleModeVisible: true,
	},
	{
		id: 'keepInvoice',
		label: 'Save invoices as a separate PDF',
		group: 'Extras',
		controlType: 'toggle',
		default: false,
		helpText: 'The cropped-off tax invoices, one per page, as their own download.',
		visibleIf: (config) => config.cropMode !== 'full',
		simpleModeVisible: false,
	},
	{
		id: 'showOrderNumber',
		label: 'Print order number',
		group: 'Extras',
		controlType: 'toggle',
		default: false,
		helpText: 'Stamped in the corner of each label.',
		simpleModeVisible: false,
	},
	{
		id: 'showDateTime',
		label: 'Print date & time',
		group: 'Extras',
		controlType: 'toggle',
		default: false,
		simpleModeVisible: false,
	},
	{
		id: 'customText',
		label: 'Custom text',
		group: 'Extras',
		controlType: 'text',
		default: '',
		helpText: 'Printed on every label, e.g. a dispatch date or thank-you note.',
		simpleModeVisible: false,
	},
];
